## Library

In [2]:
!pip install sklearn

     |████████████████████████████████| 7.2 MB 7.1 MB/s eta 0:00:01
     |████████████████████████████████| 300 kB 5.6 MB/s eta 0:00:01
     |████████████████████████████████| 28.8 MB 13.6 MB/s eta 0:00:01
     |████████████████████████████████| 15.3 MB 9.8 MB/s eta 0:00:01
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1315 sha256=c8de27c0b7279404b1c94ab151ae49b056a93600ed563cb57b21e38faf9c371c
  Stored in directory: /Users/jaeyoungshin/Library/Caches/pip/wheels/23/9d/42/5ec745cbbb17517000a53cecc49d6a865450d1f5cb16dc8a9c
Successfully built sklearn


In [4]:
!pip install keras

  Using cached Keras-2.4.3-py2.py3-none-any.whl (36 kB)
     |████████████████████████████████| 3.0 MB 1.0 MB/s eta 0:00:01
     |████████████████████████████████| 269 kB 6.9 MB/s eta 0:00:01
  Created wheel for pyyaml: filename=PyYAML-5.3.1-cp36-cp36m-macosx_10_9_x86_64.whl size=44625 sha256=ec3af499ba6184a4a8332f13c26187512c905f759a7b5a0b8d073336cc49e62b
  Stored in directory: /Users/jaeyoungshin/Library/Caches/pip/wheels/e5/9d/ad/2ee53cf262cba1ffd8afe1487eef788ea3f260b7e6232a80fc
Successfully built pyyaml


In [6]:
!pip install tensorflow

     |████████████████████████████████| 165.1 MB 13.4 MB/s eta 0:00:01    |████████████████████████        | 124.0 MB 8.2 MB/s eta 0:00:06
     |████████████████████████████████| 28.5 MB 12.0 MB/s eta 0:00:01
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
     |████████████████████████████████| 1.3 MB 9.9 MB/s eta 0:00:01
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
     |████████████████████████████████| 3.0 MB 5.1 MB/s eta 0:00:01
  Using cached tensorboard-2.3.0-py3-none-any.whl (6.8 MB)
  Using cached termcolor-1.1.0.tar.gz (3.9 kB)
  Using cached tensorflow_estimator-2.3.0-py2.py3-none-any.whl (459 kB)
  Using cached absl-py-0.9.0.tar.gz (104 kB)
     |████████████████████████████████| 15.1 MB 12.5 MB/s eta 0:00:01
  Using cached gast-0.3.3-py2.py3-none-any.whl (9.7 kB)
  Using cached google_auth_oauthlib-0.4.1-py2.py3-none-any.

In [8]:
!pip install pandas

     |████████████████████████████████| 10.6 MB 13.5 MB/s eta 0:00:01
  Using cached pytz-2020.1-py2.py3-none-any.whl (510 kB)


In [10]:
!pip install gensim

     |████████████████████████████████| 24.2 MB 11.7 MB/s eta 0:00:01
  Using cached smart_open-2.1.0.tar.gz (116 kB)
     |████████████████████████████████| 1.4 MB 15.6 MB/s eta 0:00:01
     |████████████████████████████████| 97 kB 11.0 MB/s eta 0:00:01
     |████████████████████████████████| 6.5 MB 9.9 MB/s eta 0:00:01
  Using cached jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
  Using cached s3transfer-0.3.3-py2.py3-none-any.whl (69 kB)
  Using cached docutils-0.15.2-py3-none-any.whl (547 kB)
  Created wheel for smart-open: filename=smart_open-2.1.0-py3-none-any.whl size=110317 sha256=524e709ed110fdf27116c2c1aafb82171f7f0d85844ac72f53276b11c0be5264
  Stored in directory: /Users/jaeyoungshin/Library/Caches/pip/wheels/a4/9b/d5/85705a7ab783cd6f7bd718f01d3b1396272f30044e3c36401a
  Created wheel for boto3: filename=boto3-1.14.39-py2.py3-none-any.whl size=127851 sha256=8c7c1ac25dfdcd556d042404803a8ac3c0525e1a91a4853c191c6732313989c8
  Stored in directory: /Users/jaeyoungshin/Library/Cache

In [12]:
!pip install konlpy

  Using cached konlpy-0.5.2-py2.py3-none-any.whl (19.4 MB)
  Using cached tweepy-3.9.0-py2.py3-none-any.whl (30 kB)
     |████████████████████████████████| 4.5 MB 1.0 MB/s eta 0:00:01
     |████████████████████████████████| 401 kB 8.8 MB/s eta 0:00:01
  Using cached colorama-0.4.3-py2.py3-none-any.whl (15 kB)
  Using cached beautifulsoup4-4.6.0-py3-none-any.whl (86 kB)
  Using cached typing_extensions-3.7.4.2-py3-none-any.whl (22 kB)
  Using cached PySocks-1.7.1-py3-none-any.whl (16 kB)


In [1]:
from sklearn.feature_extraction.text import CountVectorizer
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Model
from keras.layers import *
import tensorflow as tf
import numpy as np
import pandas as pd
from gensim import models
from konlpy.tag import Mecab
import re

## word2vec model (300 dimension)

In [2]:
mecab_model = models.word2vec.Word2Vec.load('/Users/jaeyoungshin/Desktop/NLP/cnn_2조/mecab_model_files/word2vec_ modeling/NaverMovie_mecab300.model')

## train/test set

In [3]:
train_data = pd.read_csv('/Users/jaeyoungshin/Desktop/NLP/cnn_2조/prep for modeling/ratings_train.txt',sep='\t').dropna().reset_index(drop=True)
test_data = pd.read_csv('/Users/jaeyoungshin/Desktop/NLP/cnn_2조/prep for modeling/ratings_test.txt',sep='\t').dropna().reset_index(drop=True)

training_sentences = []
testing_sentences = []

In [4]:
stopwords_df = pd.read_excel('/Users/jaeyoungshin/Desktop/NLP/cnn_2조/prep for modeling/stopwords.xlsx')
stopwords_list = stopwords_df['불용어'].tolist()

In [5]:
mecab = Mecab()

In [6]:
train_data['document'] = train_data['document'].str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]","")
test_data['document'] = test_data['document'].str.replace("[^ㄱ-ㅎㅏ-ㅣ가-힣 ]","")

In [7]:
documents = []
for item in train_data.document:
    documents.append([word for word in [tokens[0] for tokens in mecab.pos(item)] if word not in stopwords_list])

labels = []
for item in train_data.label:
    labels.append(item)

In [8]:
test_documents = []
for item in test_data.document:
    test_documents.append([word for word in [tokens[0] for tokens in mecab.pos(item)] if word not in stopwords_list])

test_labels = []
for item in test_data.label:
    test_labels.append(item)

In [9]:
training_labels_final = np.array(labels)
testing_labels_final = np.array(test_labels)

## Padding

In [10]:
vocab_size = 20000
embedding_dim = 300
max_length = 41
oov_tok = '<OOV>'

tokenizer = Tokenizer(num_words = vocab_size, oov_token=oov_tok)
tokenizer.fit_on_texts(documents)

In [11]:
testing_sequences = tokenizer.texts_to_sequences(test_documents)
test_padded = pad_sequences(testing_sequences, maxlen=max_length)

In [12]:
word_index = tokenizer.word_index
text_sequences = tokenizer.texts_to_sequences(documents)
padded = pad_sequences(text_sequences,maxlen=max_length,truncating = 'pre')

## save tokenizer as pickle file

In [14]:
import pickle

In [15]:
with open('tokenizer_mecab300_l2.pickle', 'wb') as handle:
    pickle.dump(tokenizer, handle, protocol=pickle.HIGHEST_PROTOCOL)

## save parameters as json file

In [16]:
import json
from collections import OrderedDict

file_data = OrderedDict()
file_data['max_len'] = 41
file_data['pad_type'] = "pre"
file_data['trunc_type'] = "pre"

In [17]:
print(json.dumps(file_data, ensure_ascii=False, indent='\t'))

{
	"max_len": 41,
	"pad_type": "pre",
	"trunc_type": "pre"
}


In [18]:
with open('w2v_mecab300_l2.json','w',encoding='utf-8') as make_file:
    json.dump(file_data, make_file, ensure_ascii=False, indent='\t')

## Embedding Matrix

In [13]:
embedding_matrix = np.zeros((vocab_size, embedding_dim))

index = 0 
for word, idx in tokenizer.word_index.items():
    try:
        embedding_vector = mecab_model.wv.__getitem__(word)
        if embedding_vector is not None:
            embedding_matrix[idx] = embedding_vector
    except Exception as e:
        pass
        
embedding_matrix.shape

(20000, 300)

## Layers

In [14]:
sequence_input = tf.keras.Input(shape=(max_length,), dtype='int32')
embedding_layer = tf.keras.layers.Embedding(vocab_size,
                            embedding_dim,
                            input_length=max_length,
                            trainable=False)
embedded_sequences = embedding_layer(sequence_input)
convs = []
filter_sizes = [3,4,5]
for fsz in filter_sizes:
    x = tf.keras.layers.Conv1D(128, fsz, activation='relu',padding='same')(embedded_sequences)
    x = tf.keras.layers.MaxPooling1D()(x)
    convs.append(x)
x = tf.keras.layers.Concatenate(axis=-1)(convs)
x = tf.keras.layers.Flatten()(x)
x = tf.keras.layers.Dense(128, activation='relu',kernel_regularizer=tf.keras.regularizers.l2(0.02))(x)
x = tf.keras.layers.Dropout(0.5)(x)
output = tf.keras.layers.Dense(1, activation='sigmoid')(x)
model = tf.keras.Model(sequence_input, output)
model.layers[1].set_weights([embedding_matrix])
model.layers[1].trainable=False
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

## Training

In [15]:
from keras.callbacks import EarlyStopping
es = EarlyStopping(monitor='val_accuracy',min_delta=0.002,patience=1,mode='max')

In [16]:
num_epochs = 30
history = model.fit(padded, training_labels_final, epochs = num_epochs, validation_data = (test_padded, testing_labels_final), callbacks=[es])
history

Epoch 1/30
4688/4688 [==============================] - 149s 32ms/step - loss: 0.4662 - accuracy: 0.8321 - val_loss: 0.4384 - val_accuracy: 0.8428
Epoch 2/30
4688/4688 [==============================] - 185s 40ms/step - loss: 0.4325 - accuracy: 0.8526 - val_loss: 0.4501 - val_accuracy: 0.8440


In [17]:
sentence = ["수면제인가 꿀잠잤음","바보같은 영화","조금 기대 이하이긴 했는데 그래도 만족함", "완전 재밌었다", "개꿀잼"]
sequence_exp = tokenizer.texts_to_sequences(sentence)
padded_exp = pad_sequences(sequence_exp, maxlen = max_length, truncating= 'post')
print(model.predict(padded_exp).round(2))

[[0.5 ]
 [0.4 ]
 [0.65]
 [0.64]
 [0.5 ]]


## Save model

In [18]:
model.save('word2vec_mecab300_updated_l2_w2v/0.8440_model')

Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
INFO:tensorflow:Assets written to: word2vec_mecab300_updated_l2_w2v/0.8440_model/assets


**load saved model / re-training**

In [19]:
mecab_model = tf.keras.models.load_model('word2vec_mecab300_updated_l2_w2v/0.8440_model')

In [20]:
from keras.callbacks import EarlyStopping
re_es = EarlyStopping(monitor='val_accuracy',min_delta=0.002,mode='max')

In [21]:
re_history = mecab_model.fit(padded, training_labels_final, epochs = num_epochs, validation_data = (test_padded, testing_labels_final), callbacks=[re_es])
re_history

Epoch 1/30
4688/4688 [==============================] - 484s 103ms/step - loss: 0.4229 - accuracy: 0.8600 - val_loss: 0.4238 - val_accuracy: 0.8572
Epoch 2/30
4688/4688 [==============================] - 494s 105ms/step - loss: 0.3545 - accuracy: 0.8952 - val_loss: 0.4464 - val_accuracy: 0.8539


**re-training model save (val_accuracy : 0.8539)**

In [22]:
mecab_model.save('word2vec_mecab300_updated_l2_w2v/0.8539_model')

INFO:tensorflow:Assets written to: word2vec_mecab300_updated_l2_w2v/0.8539_model/assets


In [23]:
mecab_remodel = tf.keras.models.load_model('word2vec_mecab300_updated_l2_w2v/0.8539_model')

In [60]:
# 0.7993
sentence = ["완전 추천함","아 겁나 지루했음 개비추..","에라이 때려쳐 이게 영화라고?",'내 인생 영화']
sequence_exp = tokenizer.texts_to_sequences(sentence)
padded_exp = pad_sequences(sequence_exp, maxlen = max_length, truncating= 'post')
print(mecab_remodel.predict(padded_exp).round(2))

[[0.99]
 [0.05]
 [0.02]
 [0.76]]


In [41]:
# 0.8468
sentence = ["완전 추천함","아 겁나 지루했음 개비추..","에라이 때려쳐 이게 영화라고?",'내 인생 영화']
sequence_exp = tokenizer.texts_to_sequences(sentence)
padded_exp = pad_sequences(sequence_exp, maxlen = max_length, truncating= 'post')
print(mecab_remodel.predict(padded_exp).round(2))

[[0.57]
 [0.63]
 [0.08]
 [0.89]]


In [24]:
# 0.8539
sentence = ["완전 추천함","아 겁나 지루했음 개비추..","에라이 때려쳐 이게 영화라고?",'내 인생 영화']
sequence_exp = tokenizer.texts_to_sequences(sentence)
padded_exp = pad_sequences(sequence_exp, maxlen = max_length, truncating= 'post')
print(mecab_remodel.predict(padded_exp).round(2))

[[0.66]
 [0.51]
 [0.04]
 [0.88]]
